import { useEffect, useState } from "react";
import { apiFetch } from "./api";

type Cert = { id:number; certPath:string; domains:string[]; expiresAt:number|null; issuer:string; lastScanAt:number; lastRenewAt:number|null; status:string; lastError:string };
type ScanInfo = { user?:string; uid?:string; openssl?:string; nginx?:string; sudo?:string; nginxConfig?:string; candidates?:string; certificates?:string };
type Machine = { id:number; name:string; sshHost:string; sshPort:number; sshUser:string; sshAuthType:string; sshTrusted:number };
type Config = { email:string; cfTokenMasked:string; cfAccountId:string; autoRenew:boolean; autoRenewDays:number; configured:boolean };

function date(ms:number|null) { return ms ? new Date(ms).toLocaleString() : "—"; }
export function CertificatesPage() {
  const [config,setConfig]=useState<Config|null>(null); const [email,setEmail]=useState("yamatu@qq.com");
  const [token,setToken]=useState(""); const [account,setAccount]=useState(""); const [autoRenew,setAutoRenew]=useState(true); const [autoRenewDays,setAutoRenewDays]=useState(30); const [machines,setMachines]=useState<Machine[]>([]);
  const [selected,setSelected]=useState<number>(0); const [certs,setCerts]=useState<Cert[]>([]); const [scanInfo,setScanInfo]=useState<ScanInfo|null>(null); const [busy,setBusy]=useState(false); const [message,setMessage]=useState("");
  const loadConfig=()=>apiFetch<Config>("/api/certificates/config").then(c=>{setConfig(c);setEmail(c.email||"yamatu@qq.com");setAccount(c.cfAccountId||"");setAutoRenew(c.autoRenew);setAutoRenewDays(c.autoRenewDays||30);});
  useEffect(()=>{ void Promise.all([loadConfig(),apiFetch<{machines:Machine[]}>("/api/certificates/machines").then(r=>setMachines(r.machines))]); },[]);
  const loadCertsFor=(id:number)=>apiFetch<{certificates:Cert[]}>(`/api/certificates/machine/${id}`).then(r=>{setCerts(r.certificates);setSelected(id);});
  const loadCerts=()=>selected?loadCertsFor(selected):Promise.resolve();
  useEffect(()=>{void loadCerts();},[selected]);
  async function save(){setBusy(true);setMessage("");try{await apiFetch("/api/certificates/config",{method:"PUT",body:JSON.stringify({email,cfToken:token||undefined,cfAccountId:account,autoRenew,autoRenewDays})});setToken("");await loadConfig();setMessage("Cloudflare 配置已保存");}catch(e:any){setMessage(`保存失败：${e.message}`)}finally{setBusy(false)}}
  async function scanFor(id:number){setBusy(true);setSelected(id);setMessage("");setScanInfo(null);try{const r=await apiFetch<{found:number;warning?:string;info?:ScanInfo}>(`/api/certificates/machine/${id}/scan`,{method:"POST",body:"{}"});await loadCertsFor(id);setScanInfo(r.info||null);setMessage(r.warning||`扫描完成，发现 ${r.found} 个证书`)}catch(e:any){setMessage(`扫描失败：${e.message}`)}finally{setBusy(false)}}
  async function scan(){if(selected) await scanFor(selected)}
  async function renew(c:Cert){if(!confirm(`确认申请并更新 ${c.domains.join(", ")}？将执行 nginx -t 后 reload。`))return;setBusy(true);setMessage("");try{await apiFetch(`/api/certificates/machine/${selected}/renew`,{method:"POST",body:JSON.stringify({id:c.id})});await loadCerts();setMessage("证书更新成功，Nginx 已重载")}catch(e:any){setMessage(`更新失败：${e.message}`)}finally{setBusy(false)}}
  return <div className="grid gap-4">
    <div className="yaws-card p-5"><div className="mb-1 text-lg font-extrabold">证书自动管理</div><div className="mb-4 text-xs text-white/45">通过已配置 SSH 扫描常见证书目录，按证书域名使用 Cloudflare DNS 申请 Let’s Encrypt 证书。续期前会执行 nginx -t，失败不会重载。</div>
      <div className="grid gap-3 md:grid-cols-3"><div><div className="mb-1 text-xs text-white/50">注册邮箱</div><input className="yaws-input" value={email} onChange={e=>setEmail(e.target.value)} /></div><div><div className="mb-1 text-xs text-white/50">CF_Token {config?.cfTokenMasked?`(${config.cfTokenMasked})`:""}</div><input className="yaws-input" type="password" placeholder="留空表示不修改" value={token} onChange={e=>setToken(e.target.value)} /></div><div><div className="mb-1 text-xs text-white/50">CF_Account_ID</div><input className="yaws-input" value={account} onChange={e=>setAccount(e.target.value)} /></div></div>
      <div className="mt-3 flex flex-wrap items-center gap-4"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={autoRenew} onChange={e=>setAutoRenew(e.target.checked)}/> 启用到期前自动续期</label><label className="text-xs text-white/50">提前 <input className="yaws-input inline-block w-20" type="number" min={1} max={90} value={autoRenewDays} onChange={e=>setAutoRenewDays(Number(e.target.value))}/> 天</label><button className="yaws-btn-primary" disabled={busy} onClick={save}>保存配置</button><span className={`text-xs ${config?.configured?"text-emerald-300":"text-amber-300"}`}>{config?.configured?"Cloudflare DNS 已配置":"尚未配置 CF_Token / CF_Account_ID"}</span></div>
    </div>
    <div className="yaws-card p-5"><div className="mb-3 flex items-center justify-between"><div className="font-extrabold">SSH 服务器</div><div className="text-xs text-white/40">共 {machines.length} 台已配置 SSH 的服务器</div></div><div className="grid gap-3">{machines.length?machines.map(m=><div key={m.id} className={`rounded-xl border p-4 ${selected===m.id?"border-sky-400/50 bg-sky-400/[.08]":"border-white/[.08] bg-white/[.03]"}`}><div className="flex flex-wrap items-center gap-3"><button className="flex-1 text-left" onClick={()=>setSelected(m.id)}><div className="font-semibold">{m.name}</div><div className="mt-1 text-xs text-white/50">{m.sshUser}@{m.sshHost}:{m.sshPort} · {m.sshAuthType==="key"?"私钥":"密码"}</div></button><span className={`text-xs ${m.sshTrusted?"text-emerald-300":"text-amber-300"}`}>{m.sshTrusted?"SSH 指纹已信任":"需要先信任 SSH 指纹"}</span><button className="yaws-btn" disabled={!m.sshTrusted||busy} onClick={()=>{setSelected(m.id);void scanFor(m.id)}}>{busy&&selected===m.id?"扫描中…":"扫描证书"}</button><button className="yaws-btn" disabled={busy} onClick={()=>{setSelected(m.id);void loadCertsFor(m.id)}}>查看</button></div>{selected===m.id&&scanInfo?<div className="mt-3 text-xs text-white/50">扫描：{scanInfo.user||"—"} · openssl {scanInfo.openssl||"未找到"} · nginx {scanInfo.nginx||"未找到"} · 配置 {scanInfo.nginxConfig||"—"} · 候选 {scanInfo.candidates||"0"} · 证书 {scanInfo.certificates||"0"}</div>:null}</div>):<div className="rounded-lg border border-dashed border-white/10 p-5 text-sm text-white/40">没有配置 SSH 的服务器，请先到机器详情中配置 SSH。</div>}</div>{message?<div className="mt-3 yaws-alert-success">{message}</div>:null}{scanInfo?<div className="mt-3 rounded-lg border border-white/[.08] bg-black/20 p-3 text-xs text-white/50">扫描身份：{scanInfo.user||"—"}（uid {scanInfo.uid||"—"}） · openssl：{scanInfo.openssl||"未找到"} · nginx：{scanInfo.nginx||"未找到"} · 配置：{scanInfo.nginxConfig||"—"} · 候选文件：{scanInfo.candidates||"0"} · 可解析证书：{scanInfo.certificates||"0"}</div>:null}
      <div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-xs text-white/40"><tr><th className="p-2">域名</th><th className="p-2">证书路径</th><th className="p-2">到期时间</th><th className="p-2">状态</th><th className="p-2">操作</th></tr></thead><tbody>{certs.map(c=><tr key={c.id} className="border-t border-white/[.06]"><td className="p-2 text-white/85">{c.domains.join(", ")}</td><td className="max-w-xs truncate p-2 font-mono text-xs text-white/50">{c.certPath}</td><td className="p-2">{date(c.expiresAt)}</td><td className={`p-2 ${c.status==="ok"?"text-emerald-300":"text-rose-300"}`}>{c.status}{c.lastError?<div className="max-w-xs truncate text-xs">{c.lastError}</div>:null}</td><td className="p-2"><button className="yaws-btn-primary text-xs" disabled={busy||!config?.configured} onClick={()=>renew(c)}>申请/更新</button></td></tr>)}</tbody></table>{!certs.length?<div className="p-8 text-center text-sm text-white/40">暂无记录，请选择机器并扫描</div>:null}</div></div>
  </div>;
}
