const errors: Record<string, string> = {
  ssh_host_untrusted: "请先确认 SSH 主机指纹",
  ssh_host_key_changed: "SSH 主机指纹已变化，请核实服务器身份",
  ssh_authentication: "SSH 认证失败",
  ssh_not_configured: "请先在机器详情中配置 SSH",
  file_changed: "文件已变化或已存在，请重新打开后再保存",
  file_busy: "文件正在保存，请稍后重试",
  file_too_large: "文件超过大小限制",
  not_utf8_text: "非 UTF-8 文本，请下载后编辑",
  binary_file: "二进制文件不能在文本编辑器中打开",
  not_regular_file: "不支持编辑特殊文件",
  ai_not_configured: "请先配置 AI 接口和模型",
  ai_busy: "AI 任务正在运行，请稍后重试",
  ai_failed: "AI 请求失败，请检查接口设置或稍后重试",
  ai_context_limit: "读取的内容过多，请缩小问题范围",
  ai_tool_limit: "本轮操作过多，请再追问一次继续处理",
  bad_tool_arguments: "AI 生成的参数无效，请换个说法再试",
  proposal_already_handled: "这条操作已经被处理过了",
  proposal_not_applied: "只有已应用的修改才能撤销",
  confirmation_required: "需要先确认才能执行",
  not_found: "记录不存在或已被删除",
  bad_request: "请求参数不正确",
  model_dns_failed: "AI 接口域名解析失败",
  outside_workspace: "路径不在选定工作目录中",
  sensitive_file_blocked: "AI 不允许读取凭据文件",
  private_ai_endpoint_blocked: "接口指向内网地址，请检查 AI 设置",
  https_required: "AI 接口需要 HTTPS",
  workspace_timeout: "文件操作超时",
  workspace_busy: "该机器正在处理其他操作，请稍后重试",
  ssh_connect_failed: "SSH 连接失败，请检查地址、端口和防火墙",
  connect_timeout: "SSH 连接超时，请检查服务器是否可达",
  session_limit: "同时打开的终端太多了，请先关闭不用的终端",
  idle_timeout: "终端长时间没有操作，已自动断开",
  slow_client: "终端输出过快，本地无法及时处理，连接已断开",
  input_limit: "输入过快，连接已断开",
  duplicate_connect: "这个终端重复发起了连接",
  bad_message: "终端会话出现异常数据，连接已断开",
  shell_failed: "远程服务器无法启动交互式终端",
  shell_error: "远程终端出错，连接已断开",
  socket_closed: "终端连接已关闭",
  socket_error: "终端连接出错",
  ssh_error: "SSH 连接出错，请重试",
  ws_error: "终端连接中断，请重试",
  terminal_init_failed: "终端初始化失败，请刷新页面重试",
  ssh_timeout: "SSH 连接超时",
  ssh_closed: "SSH 连接已断开",
  ssh_auth_failed: "SSH 认证失败，请检查用户名和密码/密钥",
  ssh_password_missing: "未保存 SSH 密码",
  ssh_key_missing: "未保存 SSH 私钥",
  ssh_credentials_invalid: "SSH 凭据无法解密，请重新保存密码或密钥",
  ssh_key_invalid: "SSH 私钥无法解密，请重新保存密钥",
  ssh_address_changed: "SSH 地址已变化，请重新确认主机指纹",
  ssh_host_unavailable: "无法连接 SSH 主机",
  exec_failed: "远程命令执行失败",
  command_timeout_or_cancelled: "远程命令超时",
  command_output_limit: "远程命令输出过多",
  forbidden: "仅管理员可用",
  model_network_error: "AI 接口连接失败或超时",
  model_http_401: "AI 密钥无效",
  model_http_400: "AI 接口拒绝请求，请检查模型、协议和推理级别",
  model_http_404: "AI 接口路径或模型不存在",
  cancelled: "操作已取消",
  file_path_changed: "文件路径发生变化，请重新生成方案",
};
export function workspaceError(error: unknown) {
  const text = error instanceof Error ? error.message : "请求失败";
  return errors[text] ?? text;
}
